### ISSUE TITLE
Component feature request: footer with border and column-layout

### ISSUE THREAD

**Issue by AlineNap** [nl-design-system/utrecht#2555]
Please add tokens to be able to place a border at the top of the page footer and to add a column layout. The following tokens are involved:

- utrecht.page-footer.border-color
- utrecht.page-footer.border-width
- utrecht.page-footer.column-gap _of is het utrecht.page-footer.column-layout.column-gap?_
- utrecht.page-footer.max-inline-size of _*.column-layout.max-inline-size_
- utrecht.page-footer.column-width of _*.column-layout.column-width_

During the RHC sprint planning on October 2nd, Robbert confirmed that this can be added to the Utrecht code.

**Comment by AlineNap** [comment]
Zie meer info in ticket van RHC: Footer update #727

**Comment by Robbert** [comment]
Voorbeeld:

```css
.utrecht-page-footer__content {
  --utrecht-column-layout-column-gap: var(--utrecht-page-footer-content-column-gap);
  display: flex;
  column-gap: var(--utrecht-page-footer-content-column-gap);
}
```
