### ISSUE TITLE
Accordion: default minimum target size 44x44px

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/utrecht#2764]
Net als bij button, zouden we voor `utrecht-breadcrumb-nav__link` een minimum target size kunnen maken die standaard 44x44px. Daarmee voldoet het aan Niveau AAA WCAG SC 2.5.5

De button heeft:

```css
.utrecht-button {
  min-block-size: var(--utrecht-button-min-block-size, 44px);
  min-inline-size: var(--utrecht-button-min-inline-size, 44px);
}
```

Op die manier is de implemenatie ook nog bruikbaar voor de designs waarbij minder dan 44x44px noodzakelijk is.

Wanneer we dit doen, moet er ook nog extra aandacht besteed worden aan de alignment van de icons, want die staan niet meer op de juiste plek wanneer de links een ander formaat krijgen dan de separators.

<img width="391" alt="Image" src="https://github.com/user-attachments/assets/35d5cda7-2769-4e48-b59c-e6d551df4e7b" />

## Acceptatie-criteria

- [ ] design tokens zijn geimplementeerd en gedocumenteerd
- [ ] wanneer de token ingesteld word op 44x44px dan blijft het design van de tekst en de icons er mooi uit zien
