### ISSUE TITLE
The default icon size should be 1 em

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/utrecht#2794]
Suggestion: add `1em` as fallback for all uses of `--utrecht-icon-size`.

```scss
@mixin utrecht-icon {
  block-size: var(--utrecht-icon-size, 1em);
  color: var(--utrecht-icon-color, 1em);
  display: inline-block;
  font-size: var(--utrecht-icon-size, 1em);
  inline-size: var(--utrecht-icon-size, 1em);
  inset-block-start: var(--utrecht-icon-inset-block-start, 0);
  position: relative;
}
```

The SVG icon generator [already adds](https://github.com/nl-design-system/utrecht/blob/main/packages/icon/svgo.config.mjs#L24-L34) `1em` to `<svg>` elements using svgo:

```js
    {
      name: 'addAttributesToSVGElement',
      params: {
        attributes: [
          {
            fill: 'currentColor',
            height: '1em',
            width: '1em',
          },
        ],
      },
    }
```

With the change to the CSS you can use `<utrecht-icon><svg>...</svg></utrecht-icon>` even with icons that don't have `width` and `height` attributes.
