### ISSUE TITLE
currentColor for slotted svg icons in <utrecht-icon>

### ISSUE THREAD

**Issue by Robbert** [nl-design-system/utrecht#2795]
It would be nice if SVG icons would automatically assume the color of the surrounding text content.

Currently we have the following stylesheet for the web component:

```scss
::slotted(svg) {
  @include utrecht-icon__svg;
}
```

Perhaps this should become:

```scss
::slotted(svg) {
  @include utrecht-icon__svg;
  fill: currentColor;
}
```

(Or included it in the mixin directly)
